### PR TITLE
Nullsafety implementation

### PR DESCRIPTION
**Pull request by luciano-cervantes**

### CODE REVIEW

**Review by gabriel-cervantes — APPROVED** [review]

**Review by vinicios-cervantes — APPROVED** [review]
Very good

**Comment by luciano-cervantes** [comment]
thanks

**Comment by luciano-cervantes** [comment]
please review this PR @dkatalis

**Comment by dk-imudita** [comment]
Thank you for your contribution, however please wait for 1-2 weeks, currently some of our repository that using this tool is still using old dart/flutter, and currently we are in progress to upgrade it.

Kind regards,

Made

**Comment by luciano-cervantes** [comment]
All right! 😉

**Pull request merged**
